### PR TITLE
docs(publishing): add instructions for publishing new theme versions to npm

### PR DESCRIPTION
**Pull request by bdenham**
## Description

This PR adds instructions for updating any theme (or other) packages to npm for package distribution. It applies specifically to how the devsite team should publish package versions to npm without committing directly to main as is the current practice that I participated in. 

Since then, I took the time this morning to write these instructions that provide a better approach that respects `main` branch protection rules — which I applied to this repo, after having just pushed this PR to `main` accidentally! Chuckle.

NOTE: If we were to publish our our own "commerce theme" package to npm, we would need to add a workflow similar to the one used for `adobe/aio-theme`.

## Related Issue

Nothing in Jira. But there should be...

## Motivation and Context

Using best practices.

## How Has This Been Tested?

It has not. 

## Types of changes

- [x] Usage and maintenance documentation (non-breaking change which documents usage and maintenance)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by jeff-matthews — COMMENTED** [review]
Looks good. Documenting a standard, PR-based release workflow seems like table stakes. I'm surprised this doesn't already exist. 

Is the goal to propose this workflow to the devsite team? If we merge this with the main branch in our fork, will that effect how we sync with the upstream repo in the future?

**Comment by bdenham** [comment]
Good questions. I guess the ultimate goal is to have the devsite team adopt this standard. But the immediate goal is for us (Commerce team) to adopt this standard if we are again in the position to publish versions of the adobe/aio-theme from their repo. And if we feel the need to publish our own fork to npm, as a way ensure all of our commerce sites have a centralized (shared) feature set, we'll need to follow these procedures. So we need them for any one of those scenarios. 

What do y'all think?

**Comment by dshevtsov** [comment]
Maybe it makes sense to consider creating our own theme with the customizations we need in addition to the aio-theme?

**Comment by dshevtsov** [comment]
That's right. This is what the "commerce-theme" would do. But the commerce theme should depend on the "aio-theme".
But it should not be a fork of the "aio-theme", it should be a separate project.

**Comment by bdenham** [comment]
See replacement PR here: https://github.com/magento-devdocs/commerce-theme/pull/10

**Pull request closed without merging**
