### PR TITLE
Sync with upstream 

### PR DESCRIPTION
**Pull request by bdenham**
## Description

This PR syncs our fork with the upstream repo.

## Motivation and Context

To prep our team repo with the latest adobe/aio-theme so we have the option to develop features independently for commerce docs, with the option to update the upstream if the devsite team wants to incorporate our features.

## How Has This Been Tested?

It hasn't. But the upstream has been tested and is being tested now.

## Types of changes

- [x] Upstream sync (non-breaking change which fixes issues)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by jeff-matthews — APPROVED** [review]

**Review by dshevtsov — CHANGES_REQUESTED** [review]
Use Sync fork from GitHub UI instead.

**Comment by bdenham** [comment]
@dshevtsov, yeah, I actually did that. Then compared. Then created a PR for visibility and to promote conscious awareness to the changes and future development of this fork. 

Would you still like me to use the Sync automation? Assuming that it is automated without creating a PR?

**Comment by dshevtsov** [comment]
> Would you still like me to use the Sync automation? Assuming that it is automated without creating a PR?

Yes.

**Comment by dshevtsov** [comment]
@bdenham please do not use your admin permissions to overcome any requested changes.

**Pull request merged**
